In [13]:
import numpy as np
a=np.array([6,8,2,5])
b=np.arange(4)
print(b)
c=a+b
print("addn:",c)
d=a-b
print("subtrn:",d)
d=a*b
print("multipl:",d)
e=b/a
print("divsn:",e)
print("a[]*2=",a**2)
print("sinx:",10*np.sin(a))
print("a<6",a<6)

[0 1 2 3]
addn: [6 9 4 8]
subtrn: [6 7 0 2]
multipl: [ 0  8  4 15]
divsn: [0.    0.125 1.    0.6  ]
a[]*2= [36 64  4 25]
sinx: [-2.79415498  9.89358247  9.09297427 -9.58924275]
a<6 [False False  True  True]


In [20]:
a=np.array([(6,8,2),(1,2,3),(4,6,5)])
b=np.array([(1,2,3),(1,2,3),(1,2,3)])

print("elementwise:\n ",a*b)                  #elementwise product

print("matrix1:\n ",a@b)                  #matrix multiplication

print("matrix2:\n ",a.dot(b))             #matrix multiplication

elementwise:
  [[ 6 16  6]
 [ 1  4  9]
 [ 4 12 15]]
matrix1:
  [[16 32 48]
 [ 6 12 18]
 [15 30 45]]
matrix2:
  [[16 32 48]
 [ 6 12 18]
 [15 30 45]]


In [1]:
a=np.random.random((2,3))
print(a)
b=np.array([(1,2,3),(4,5,6)],dtype=int)
b*=3
a+=b
#b+=a    bcoz cant add float to int  and cant specify dtype in random func
b

NameError: name 'np' is not defined

In [24]:
import numpy as np
a=np.ones(3,dtype=np.int32)
b=np.linspace(0,3.14,3)
b.dtype.name
c=a+b
#print(c)
d=np.exp(c*1j)
sum(d)
min(d)
max(c)
c=np.arange(12).reshape(3,4)
print(c)
print(c.sum(axis=1))
c.cumsum(axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22 38]


array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)