In [23]:
import numpy as np
a = np.floor(10*np.random.random((3,4)))
print(a)
a.ravel()
a.reshape(3,4)

a.T
a.resize(2,6)
print(a)
a.reshape(3,-1)

[[3. 1. 8. 8.]
 [8. 8. 7. 7.]
 [9. 5. 1. 3.]]
[[3. 1. 8. 8. 8. 8.]
 [7. 7. 9. 5. 1. 3.]]


array([[3., 1., 8., 8.],
       [8., 8., 7., 7.],
       [9., 5., 1., 3.]])