In [4]:
#no copy at all
import numpy as np
a = np.arange(12)
b=a
print(b)
b is a
b.shape= 3,4
a.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11]


(3, 4)

In [15]:
#shallow copy
c = a.view()
c is a 
c.base is a
c.flags.owndata
c.shape = 2,6 
c
#a.shape
c[0,4] = 1234 
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [15]:
import numpy as np
a = np.arange(12)
a.resize(3,4)
print(a)
s = a[ : , 1:4]
s[:]=10
s=10
a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
d=a.copy()
d is a
d.base is a
d[0,0]=9999
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])